-- ============================================================
-- 데이터베이스 텀 프로젝트 — 중고거래 플랫폼
-- 스키마 DDL (5개 프로젝트 테이블)
--   CUSTOMER, ITEM, PURCHASEREQ, CHATROOM, MESSAGE
-- ※ 실제 운영 DB(Oracle 21c XE)에서 DBMS_METADATA로 추출한 정의이며,
--    스키마 한정자("D202202603".)는 이식성을 위해 제거함.
--   - 상태값 CHECK: ITEM.sellStatus IN ('판매 중','예약 중','거래 완료')
--   - MESSAGE.sender IN ('S','B'), isRead IN ('Y','N')
--   - CHATROOM.roomNo / MESSAGE.seqNo: IDENTITY(자동 증가)
--   - CHATROOM UNIQUE(receiveCno,cno,itemNo): 채팅방 중복 방지
-- ============================================================

  CREATE TABLE "CUSTOMER"
   (	"CNO" VARCHAR2(10),
	"PASSWD" VARCHAR2(100) NOT NULL ENABLE,
	"NICKNAME" VARCHAR2(50) NOT NULL ENABLE,
	"PHONE" VARCHAR2(20),
	"REGION" VARCHAR2(100),
	 CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CNO")
  USING INDEX  ENABLE,
	 UNIQUE ("NICKNAME")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITEM"
   (	"CNO" VARCHAR2(10),
	"ITEMNO" NUMBER,
	"TITLE" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(300),
	"CATEGORY" VARCHAR2(50) NOT NULL ENABLE,
	"PRICE" NUMBER NOT NULL ENABLE,
	"TRADEPLACE" VARCHAR2(200),
	"REGDATETIME" TIMESTAMP (6) NOT NULL ENABLE,
	"RESDATETIME" TIMESTAMP (6),
	"SELLSTATUS" VARCHAR2(20) DEFAULT '판매 중',
	"PIC1" BLOB,
	"PIC2" BLOB,
	"PIC3" BLOB,
	"FINALPRICE" NUMBER,
	 CONSTRAINT "CHK_SELL_STATUS" CHECK (sellStatus IN ('판매 중', '예약 중', '거래 완료')) ENABLE,
	 CONSTRAINT "PK_ITEM" PRIMARY KEY ("CNO", "ITEMNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ITEM_CUSTOMER" FOREIGN KEY ("CNO")
	  REFERENCES "CUSTOMER" ("CNO") ENABLE
   ) ;


  CREATE TABLE "PURCHASEREQ"
   (	"REQUESTCNO" VARCHAR2(10),
	"CNO" VARCHAR2(10),
	"ITEMNO" NUMBER,
	"REQDATETIME" TIMESTAMP (6),
	"REQPRICE" NUMBER,
	"REQMESSAGE" VARCHAR2(1000),
	 CONSTRAINT "PK_PURCHASEREQ" PRIMARY KEY ("REQUESTCNO", "CNO", "ITEMNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PURREQ_CUSTOMER" FOREIGN KEY ("REQUESTCNO")
	  REFERENCES "CUSTOMER" ("CNO") ENABLE,
	 CONSTRAINT "FK_PURREQ_ITEM" FOREIGN KEY ("CNO", "ITEMNO")
	  REFERENCES "ITEM" ("CNO", "ITEMNO") ENABLE
   ) ;


  CREATE TABLE "CHATROOM"
   (	"ROOMNO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"RECEIVECNO" VARCHAR2(10),
	"CREATEDATETIME" TIMESTAMP (6),
	"CNO" VARCHAR2(10),
	"ITEMNO" NUMBER,
	 CONSTRAINT "PK_CHATROOM" PRIMARY KEY ("ROOMNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_CHATROOM" UNIQUE ("RECEIVECNO", "CNO", "ITEMNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CHAT_CUSTOMER" FOREIGN KEY ("RECEIVECNO")
	  REFERENCES "CUSTOMER" ("CNO") ENABLE,
	 CONSTRAINT "FK_CHAT_ITEM" FOREIGN KEY ("CNO", "ITEMNO")
	  REFERENCES "ITEM" ("CNO", "ITEMNO") ENABLE
   ) ;


  CREATE TABLE "MESSAGE"
   (	"ROOMNO" NUMBER,
	"SEQNO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"SENDER" CHAR(1),
	"SENTDATETIME" TIMESTAMP (6),
	"CONTENT" VARCHAR2(2000),
	"ISREAD" CHAR(1) DEFAULT 'N',
	 CHECK (sender IN ('S', 'B')) ENABLE,
	 CHECK (isRead IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "PK_MESSAGE" PRIMARY KEY ("ROOMNO", "SEQNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_MESSAGE_CHATROOM" FOREIGN KEY ("ROOMNO")
	  REFERENCES "CHATROOM" ("ROOMNO") ENABLE
   ) ;

