// 현재 DB의 5개 테이블 데이터를 db/seed.sql (INSERT문)로 추출
import oracledb from "oracledb";
import fs from "fs";
oracledb.outFormat = oracledb.OUT_FORMAT_ARRAY;

const TS = "TO_CHAR(%, 'YYYY-MM-DD HH24:MI:SS')";
const TABLES = [
  { name: "customer", cols: ["cno", "passwd", "nickname", "phone", "region"], types: ["s", "s", "s", "s", "s"],
    sel: "cno,passwd,nickname,phone,region", order: "cno" },
  { name: "item",
    cols: ["cno", "itemNo", "title", "description", "category", "price", "tradePlace", "regDateTime", "resDateTime", "sellStatus", "finalPrice"],
    types: ["s", "n", "s", "s", "s", "n", "s", "t", "t", "s", "n"],
    sel: `cno,itemno,title,description,category,price,tradeplace,${TS.replace("%","regdatetime")},${TS.replace("%","resdatetime")},sellstatus,finalprice`,
    order: "cno,itemno" },
  { name: "purchasereq",
    cols: ["requestCno", "cno", "itemNo", "reqDateTime", "reqPrice", "reqMessage"], types: ["s", "s", "n", "t", "n", "s"],
    sel: `requestcno,cno,itemno,${TS.replace("%","reqdatetime")},reqprice,reqmessage`, order: "cno,itemno,requestcno" },
  { name: "chatroom",
    cols: ["roomNo", "receiveCno", "createDateTime", "cno", "itemNo"], types: ["n", "s", "t", "s", "n"],
    sel: `roomno,receivecno,${TS.replace("%","createdatetime")},cno,itemno`, order: "roomno" },
  { name: "message",
    cols: ["roomNo", "seqNo", "sender", "sentDateTime", "content", "isRead"], types: ["n", "n", "s", "t", "s", "s"],
    sel: `roomno,seqno,sender,${TS.replace("%","sentdatetime")},content,isread`, order: "roomno,seqno" },
];

function fmt(v, t) {
  if (v === null || v === undefined) return "NULL";
  if (t === "n") return String(v);
  if (t === "t") return `TO_TIMESTAMP('${v}', 'YYYY-MM-DD HH24:MI:SS')`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

const conn = await oracledb.getConnection({
  user: process.env.DB_USER, password: process.env.DB_PASSWORD, connectString: process.env.DB_CONNECT_STRING,
});
let out = `-- ============================================================
-- 데모 시드 데이터 (5개 테이블) — 다른 환경에서 재현용
-- 사용법(SQL Developer/sqlplus): db/schema.sql 실행 후 이 파일을 실행
--   ※ 사진(BLOB pic1~3)은 시드에 없음(NULL). identity 컬럼(roomNo/seqNo)은
--      명시값 삽입을 위해 일시적으로 GENERATED BY DEFAULT 로 바꾼다.
-- ============================================================
SET DEFINE OFF;
ALTER TABLE chatroom MODIFY (roomNo GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE message  MODIFY (seqNo  GENERATED BY DEFAULT AS IDENTITY);
DELETE FROM message;
DELETE FROM chatroom;
DELETE FROM purchasereq;
DELETE FROM item;
DELETE FROM customer;
`;
for (const t of TABLES) {
  const r = await conn.execute(`SELECT ${t.sel} FROM ${t.name} ORDER BY ${t.order}`);
  out += `\n-- ${t.name} (${r.rows.length})\n`;
  for (const row of r.rows) {
    const vals = row.map((v, i) => fmt(v, t.types[i])).join(", ");
    out += `INSERT INTO ${t.name} (${t.cols.join(", ")}) VALUES (${vals});\n`;
  }
}
out += `\nCOMMIT;\n`;
await conn.close();
fs.writeFileSync("/Users/workspace/dev/claude/db/seed.sql", out);
console.log("db/seed.sql 생성:", out.split("\n").length, "줄");
